#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ControleAcesso.Android.Resource", IsApplication=true)]

namespace ControleAcesso.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ControleAcesso.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ControleAcesso.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ControleAcesso.Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aguarde = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendario = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int carrinho = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int configurarpermissao = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int defaultLock = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int defaultUser = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int entrada = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int entradanew = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int entradaseta = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int evento = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int fundobeta = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int garrafa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icone = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int link = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int linknew = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int money = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int permissaousuario = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int pulseirabranca = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int qrcode = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int remove = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int security = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int soundOn = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int syncbranca = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ticketbranca = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int usuarioadd = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int usuarioconfig = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int usuarios = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int venda = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int visualizar = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060035
			public const int MyButton = 2131099701;
			
			// aapt resource value: 0x7f06001f
			public const int btnBuscarCadUsuario = 2131099679;
			
			// aapt resource value: 0x7f06003d
			public const int btnBuscarProdutoPedidoEntrada = 2131099709;
			
			// aapt resource value: 0x7f060007
			public const int btnBuscarUsuarioRegistroPulseira = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int btnCadastrarEvento = 2131099668;
			
			// aapt resource value: 0x7f06003e
			public const int btnCarrinhoPedidoEntrada = 2131099710;
			
			// aapt resource value: 0x7f060022
			public const int btnFinalizarCompraCarrinho = 2131099682;
			
			// aapt resource value: 0x7f060034
			public const int btnLogarLogin = 2131099700;
			
			// aapt resource value: 0x7f060020
			public const int btnProximoPasso2 = 2131099680;
			
			// aapt resource value: 0x7f060032
			public const int btnVozLogin = 2131099698;
			
			// aapt resource value: 0x7f060048
			public const int contentFrame = 2131099720;
			
			// aapt resource value: 0x7f06001b
			public const int edtCPFCadUsuario = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int edtDataCadUsuario = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int edtEmailCadUsuario = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int edtNomeCadUsuario = 2131099669;
			
			// aapt resource value: 0x7f060033
			public const int edtSenhaLogin = 2131099699;
			
			// aapt resource value: 0x7f060017
			public const int edtTelefoneCadUsuario = 2131099671;
			
			// aapt resource value: 0x7f060031
			public const int edtUsuarioLogin = 2131099697;
			
			// aapt resource value: 0x7f060010
			public const int edtValorFretePasso2 = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int edtValorProdutoPasso2 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int edtValorSeguroPasso2 = 2131099666;
			
			// aapt resource value: 0x7f060038
			public const int imgMenuListItem = 2131099704;
			
			// aapt resource value: 0x7f06001c
			public const int layoutDescontoIncondiPasso2 = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int layoutDespesasAcessoriasPasso2 = 2131099672;
			
			// aapt resource value: 0x7f060002
			public const int layoutPrincipalBuscaCodigoNCM = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int layoutPrincipalPasso2 = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int layoutTipo = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int layoutValorFretePasso2 = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int layoutValorProduto = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int layoutbtnPasso2 = 2131099667;
			
			// aapt resource value: 0x7f06002f
			public const int lblDataEventoList = 2131099695;
			
			// aapt resource value: 0x7f06002a
			public const int lblDescricaoEventoList = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int lblLocalEventoList = 2131099693;
			
			// aapt resource value: 0x7f060024
			public const int lblNome = 2131099684;
			
			// aapt resource value: 0x7f060001
			public const int lblNomeOrdemServico = 2131099649;
			
			// aapt resource value: 0x7f060028
			public const int linarLayoutListAux = 2131099688;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060025
			public const int linearLayout2 = 2131099685;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout2Passo2 = 2131099662;
			
			// aapt resource value: 0x7f060039
			public const int linearLayout3 = 2131099705;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout3Passo2 = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout4 = 2131099648;
			
			// aapt resource value: 0x7f060027
			public const int lstCESTlist = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int lstEventos = 2131099686;
			
			// aapt resource value: 0x7f060036
			public const int lstMenu = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int lstMenuList = 2131099703;
			
			// aapt resource value: 0x7f060042
			public const int lstProdutos = 2131099714;
			
			// aapt resource value: 0x7f060023
			public const int lstProdutosEntradaPedido = 2131099683;
			
			// aapt resource value: 0x7f060008
			public const int lstUsuario = 2131099656;
			
			// aapt resource value: 0x7f060029
			public const int tableLayout1 = 2131099689;
			
			// aapt resource value: 0x7f06003c
			public const int txtBuscaProdutoCaixa = 2131099708;
			
			// aapt resource value: 0x7f060006
			public const int txtCPFRegistroPulseira = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int txtCodigoNCMFiltro = 2131099651;
			
			// aapt resource value: 0x7f060047
			public const int txtCpfUsuarioList = 2131099719;
			
			// aapt resource value: 0x7f060030
			public const int txtDataEventoList = 2131099696;
			
			// aapt resource value: 0x7f06002c
			public const int txtDescricaoEventoList = 2131099692;
			
			// aapt resource value: 0x7f06003b
			public const int txtDescricaoMenuListItem = 2131099707;
			
			// aapt resource value: 0x7f06003f
			public const int txtDescricaoProdutoList = 2131099711;
			
			// aapt resource value: 0x7f06001d
			public const int txtDespesaIncondiPasso2 = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int txtDespesasAcessoriasPasso2 = 2131099674;
			
			// aapt resource value: 0x7f060046
			public const int txtEmailUsuarioList = 2131099718;
			
			// aapt resource value: 0x7f06002e
			public const int txtLocalEventoList = 2131099694;
			
			// aapt resource value: 0x7f060041
			public const int txtNome = 2131099713;
			
			// aapt resource value: 0x7f060045
			public const int txtNomeUsuarioList = 2131099717;
			
			// aapt resource value: 0x7f060044
			public const int txtQuantidadeProdutoList = 2131099716;
			
			// aapt resource value: 0x7f06000b
			public const int txtTipoCFOPFiltro = 2131099659;
			
			// aapt resource value: 0x7f06003a
			public const int txtTituloMenuListItem = 2131099706;
			
			// aapt resource value: 0x7f060043
			public const int txtValorBetaProdutoList = 2131099715;
			
			// aapt resource value: 0x7f060021
			public const int txtValorCarrinho = 2131099681;
			
			// aapt resource value: 0x7f06000f
			public const int txtValorFretePasso2 = 2131099663;
			
			// aapt resource value: 0x7f060040
			public const int txtValorProdutoList = 2131099712;
			
			// aapt resource value: 0x7f060011
			public const int txtValorSeguroPasso2 = 2131099665;
			
			// aapt resource value: 0x7f06002b
			public const int view2 = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Aguarde = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BuscarUsuario = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CadastroEvento = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CadastroUsuario = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Carrinho = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Evento = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EventoList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Menu = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MenuList = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PedidoEntrada = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PedidoEntradaList = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Produto = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ProdutoList = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ProdutoListResumo = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Pulseira = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PulseiraList = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int RegistrarPulseira = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Usuario = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int UsuarioList = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int zxingscanneractivitylayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int zxingscannerfragmentlayout = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050011
			public const int Divider = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Divider_invisible = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int btnDeleteStyle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int btnStyle = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int cabecalhoGrid = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int cabecalhoGrid_Text = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int cabecalhoInformacoes = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int descricao = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int editText = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int headerLeft = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int headerRight = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int inserirApt = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int linearLista = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int linearPrincipal = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int linearPrincipal2 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int lista = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int lista_TituloItem = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int lista_item = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int titulo = 2131034127;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
